#!/usr/bin/env python3
"""批量生成 VSCode 主题文件，基于 iTerm2-Color-Schemes 中的热门主题配色。"""

import json
import os

THEMES_DIR = os.path.join(os.path.dirname(__file__), "themes")

# ============================================================
# 主题配色定义：每个主题包含 colors(UI) + tokenColors(语法高亮)
# 基于 iTerm2-Color-Schemes 的标志性配色
# ============================================================

THEMES = {}

# ----------------------------------------------------------
# 1. Dracula
# ----------------------------------------------------------
THEMES["dracula"] = {
    "name": "Dracula Official",
    "type": "dark",
    "colors": {
        "editor.background": "#282A36", "editor.foreground": "#F8F8F2",
        "editorLineNumber.foreground": "#6272A4", "editorLineNumber.activeForeground": "#FF79C6",
        "editor.selectionBackground": "#44475A", "editor.selectionHighlightBackground": "#44475A80",
        "editor.findMatchBackground": "#FFB86C80", "editor.findMatchHighlightBackground": "#FFB86C40",
        "editorCursor.foreground": "#F8F8F0", "editor.lineHighlightBackground": "#44475A40",
        "editorIndentGuide.background": "#6272A440", "editorIndentGuide.activeBackground": "#6272A4",
        "editorBracketMatch.border": "#FF79C680", "editorGutter.background": "#282A36",
        "editorWidget.background": "#21222C", "editorWidget.border": "#44475A",
        "editorSuggestWidget.background": "#21222C", "editorSuggestWidget.border": "#44475A",
        "editorSuggestWidget.selectedBackground": "#44475A",
        "editorHoverWidget.background": "#21222C", "editorHoverWidget.border": "#44475A",
        "editorGroup.border": "#44475A", "editorGroupHeader.tabsBackground": "#21222C",
        "tab.activeBackground": "#282A36", "tab.activeForeground": "#F8F8F2",
        "tab.inactiveBackground": "#21222C", "tab.inactiveForeground": "#6272A4",
        "tab.border": "#44475A", "tab.activeBorderTop": "#FF79C6",
        "sideBar.background": "#21222C", "sideBar.foreground": "#BFBFBF",
        "sideBar.border": "#44475A", "sideBarTitle.foreground": "#F8F8F2",
        "sideBarSectionHeader.background": "#282A36",
        "list.activeSelectionBackground": "#44475A", "list.activeSelectionForeground": "#F8F8F2",
        "list.inactiveSelectionBackground": "#44475A80", "list.hoverBackground": "#44475A40",
        "list.foreground": "#BFBFBF",
        "activityBar.background": "#191A21", "activityBar.foreground": "#F8F8F2",
        "activityBar.activeBorder": "#FF79C6", "activityBarBadge.background": "#FF79C6",
        "activityBarBadge.foreground": "#191A21",
        "statusBar.background": "#191A21", "statusBar.foreground": "#F8F8F2",
        "statusBar.debuggingBackground": "#FF79C6",
        "titleBar.activeBackground": "#21222C", "titleBar.activeForeground": "#F8F8F2",
        "menu.background": "#21222C", "menu.foreground": "#F8F8F2",
        "menu.selectionBackground": "#44475A", "menu.separatorBackground": "#44475A",
        "button.background": "#FF79C6", "button.foreground": "#282A36",
        "button.hoverBackground": "#FF92D0",
        "input.background": "#21222C", "input.border": "#44475A", "input.foreground": "#F8F8F2",
        "dropdown.background": "#21222C", "dropdown.border": "#44475A",
        "scrollbarSlider.background": "#6272A440", "scrollbarSlider.hoverBackground": "#6272A460",
        "panel.background": "#21222C", "panel.border": "#44475A",
        "terminal.background": "#282A36", "terminal.foreground": "#F8F8F2",
        "gitDecoration.addedResourceForeground": "#50FA7B",
        "gitDecoration.modifiedResourceForeground": "#FFB86C",
        "gitDecoration.deletedResourceForeground": "#FF5555",
        "gitDecoration.untrackedResourceForeground": "#50FA7B",
        "gitDecoration.ignoredResourceForeground": "#6272A4",
        "gitDecoration.conflictResourceForeground": "#FFB86C",
        "badge.background": "#FF79C6", "badge.foreground": "#282A36",
        "progressBar.background": "#FF79C6", "focusBorder": "#FF79C680",
        "foreground": "#F8F8F2", "errorForeground": "#FF5555",
        "textLink.foreground": "#8BE9FD", "icon.foreground": "#6272A4",
        "widget.shadow": "#00000060",
    },
    "tokens": [
        {"name": "Comment", "scope": ["comment", "punctuation.definition.comment"], "fg": "#6272A4", "style": "italic"},
        {"name": "String", "scope": ["string"], "fg": "#F1FA8C"},
        {"name": "Number", "scope": ["constant.numeric"], "fg": "#BD93F9"},
        {"name": "Boolean/Null", "scope": ["constant.language.boolean", "constant.language.null"], "fg": "#BD93F9"},
        {"name": "Keyword", "scope": ["keyword", "keyword.control"], "fg": "#FF79C6"},
        {"name": "Storage/Modifier", "scope": ["storage", "storage.type", "storage.modifier"], "fg": "#FF79C6"},
        {"name": "Function", "scope": ["entity.name.function", "support.function"], "fg": "#50FA7B"},
        {"name": "Class/Type", "scope": ["entity.name.type", "entity.name.class", "support.type", "support.class"], "fg": "#8BE9FD"},
        {"name": "Variable", "scope": ["variable"], "fg": "#F8F8F2"},
        {"name": "Parameter", "scope": ["variable.parameter"], "fg": "#FFB86C"},
        {"name": "Property", "scope": ["variable.other.property"], "fg": "#FFB86C"},
        {"name": "Constant", "scope": ["variable.other.constant"], "fg": "#BD93F9"},
        {"name": "Tag", "scope": ["entity.name.tag"], "fg": "#FF79C6"},
        {"name": "Attribute", "scope": ["entity.other.attribute-name"], "fg": "#50FA7B"},
        {"name": "Punctuation", "scope": ["punctuation", "meta.brace"], "fg": "#F8F8F2"},
        {"name": "Operator", "scope": ["keyword.operator"], "fg": "#FF79C6"},
        {"name": "Decorator", "scope": ["meta.decorator", "entity.name.function.decorator"], "fg": "#50FA7B"},
        {"name": "JSON Key", "scope": ["meta.object-literal.key", "support.type.property-name.json"], "fg": "#8BE9FD"},
        {"name": "CSS Property", "scope": ["support.type.property-name.css"], "fg": "#8BE9FD"},
        {"name": "CSS Value", "scope": ["support.constant.property-value.css"], "fg": "#BD93F9"},
        {"name": "HTML Tag", "scope": ["entity.name.tag.html"], "fg": "#FF79C6"},
        {"name": "Markdown Heading", "scope": ["markup.heading"], "fg": "#BD93F9", "style": "bold"},
        {"name": "Markdown Bold", "scope": ["markup.bold"], "fg": "#FF79C6", "style": "bold"},
        {"name": "Markdown Italic", "scope": ["markup.italic"], "fg": "#FFB86C", "style": "italic"},
        {"name": "Markdown Link", "scope": ["markup.underline.link"], "fg": "#8BE9FD"},
        {"name": "Markdown Code", "scope": ["markup.raw.code"], "fg": "#50FA7B"},
        {"name": "Regex", "scope": ["string.regexp"], "fg": "#F1FA8C"},
        {"name": "Invalid", "scope": ["invalid", "invalid.illegal"], "fg": "#FF5555", "style": "underline"},
        {"name": "Diff Added", "scope": ["markup.inserted", "diff.inserted"], "fg": "#50FA7B"},
        {"name": "Diff Deleted", "scope": ["markup.deleted", "diff.deleted"], "fg": "#FF5555"},
        {"name": "Diff Modified", "scope": ["markup.changed", "diff.changed"], "fg": "#FFB86C"},
    ]
}

# ----------------------------------------------------------
# 2. Tokyo Night
# ----------------------------------------------------------
THEMES["tokyo-night"] = {
    "name": "Tokyo Night",
    "type": "dark",
    "colors": {
        "editor.background": "#1A1B26", "editor.foreground": "#A9B1D6",
        "editorLineNumber.foreground": "#3B4261", "editorLineNumber.activeForeground": "#7AA2F7",
        "editor.selectionBackground": "#33467C", "editor.selectionHighlightBackground": "#2A3B5880",
        "editor.findMatchBackground": "#E0AF6880", "editor.findMatchHighlightBackground": "#E0AF6840",
        "editorCursor.foreground": "#C0CAF5", "editor.lineHighlightBackground": "#1F2335",
        "editorIndentGuide.background": "#2F3449", "editorIndentGuide.activeBackground": "#737AA2",
        "editorBracketMatch.border": "#7AA2F780", "editorGutter.background": "#1A1B26",
        "editorWidget.background": "#16161E", "editorWidget.border": "#2F3449",
        "editorSuggestWidget.background": "#16161E", "editorSuggestWidget.border": "#2F3449",
        "editorSuggestWidget.selectedBackground": "#33467C",
        "editorHoverWidget.background": "#16161E", "editorHoverWidget.border": "#2F3449",
        "editorGroup.border": "#2F3449", "editorGroupHeader.tabsBackground": "#16161E",
        "tab.activeBackground": "#1A1B26", "tab.activeForeground": "#C0CAF5",
        "tab.inactiveBackground": "#16161E", "tab.inactiveForeground": "#565F89",
        "tab.border": "#2F3449", "tab.activeBorderTop": "#7AA2F7",
        "sideBar.background": "#16161E", "sideBar.foreground": "#A9B1D6",
        "sideBar.border": "#2F3449", "sideBarTitle.foreground": "#C0CAF5",
        "sideBarSectionHeader.background": "#1A1B26",
        "list.activeSelectionBackground": "#33467C", "list.activeSelectionForeground": "#C0CAF5",
        "list.inactiveSelectionBackground": "#2A3B58", "list.hoverBackground": "#1F2335",
        "list.foreground": "#A9B1D6",
        "activityBar.background": "#16161E", "activityBar.foreground": "#7AA2F7",
        "activityBar.activeBorder": "#7AA2F7", "activityBarBadge.background": "#7AA2F7",
        "activityBarBadge.foreground": "#16161E",
        "statusBar.background": "#16161E", "statusBar.foreground": "#A9B1D6",
        "statusBar.debuggingBackground": "#F7768E",
        "titleBar.activeBackground": "#16161E", "titleBar.activeForeground": "#A9B1D6",
        "menu.background": "#16161E", "menu.foreground": "#A9B1D6",
        "menu.selectionBackground": "#33467C", "menu.separatorBackground": "#2F3449",
        "button.background": "#7AA2F7", "button.foreground": "#16161E",
        "button.hoverBackground": "#89B4FA",
        "input.background": "#16161E", "input.border": "#2F3449", "input.foreground": "#C0CAF5",
        "dropdown.background": "#16161E", "dropdown.border": "#2F3449",
        "scrollbarSlider.background": "#3B426140", "scrollbarSlider.hoverBackground": "#3B426160",
        "panel.background": "#16161E", "panel.border": "#2F3449",
        "terminal.background": "#1A1B26", "terminal.foreground": "#A9B1D6",
        "gitDecoration.addedResourceForeground": "#9ECE6A",
        "gitDecoration.modifiedResourceForeground": "#E0AF68",
        "gitDecoration.deletedResourceForeground": "#F7768E",
        "gitDecoration.untrackedResourceForeground": "#9ECE6A",
        "gitDecoration.ignoredResourceForeground": "#565F89",
        "gitDecoration.conflictResourceForeground": "#E0AF68",
        "badge.background": "#7AA2F7", "badge.foreground": "#16161E",
        "progressBar.background": "#7AA2F7", "focusBorder": "#7AA2F780",
        "foreground": "#A9B1D6", "errorForeground": "#F7768E",
        "textLink.foreground": "#7AA2F7", "icon.foreground": "#565F89",
        "widget.shadow": "#00000060",
    },
    "tokens": [
        {"name": "Comment", "scope": ["comment"], "fg": "#565F89", "style": "italic"},
        {"name": "String", "scope": ["string"], "fg": "#9ECE6A"},
        {"name": "Number", "scope": ["constant.numeric"], "fg": "#FF9E64"},
        {"name": "Boolean/Null", "scope": ["constant.language.boolean", "constant.language.null"], "fg": "#FF9E64"},
        {"name": "Keyword", "scope": ["keyword", "keyword.control"], "fg": "#BB9AF7"},
        {"name": "Storage/Modifier", "scope": ["storage", "storage.type"], "fg": "#BB9AF7"},
        {"name": "Function", "scope": ["entity.name.function", "support.function"], "fg": "#7AA2F7"},
        {"name": "Class/Type", "scope": ["entity.name.type", "entity.name.class", "support.type"], "fg": "#2AC3DE"},
        {"name": "Variable", "scope": ["variable"], "fg": "#C0CAF5"},
        {"name": "Parameter", "scope": ["variable.parameter"], "fg": "#E0AF68"},
        {"name": "Property", "scope": ["variable.other.property"], "fg": "#7DCFFF"},
        {"name": "Constant", "scope": ["variable.other.constant"], "fg": "#FF9E64"},
        {"name": "Tag", "scope": ["entity.name.tag"], "fg": "#F7768E"},
        {"name": "Attribute", "scope": ["entity.other.attribute-name"], "fg": "#BB9AF7"},
        {"name": "Punctuation", "scope": ["punctuation", "meta.brace"], "fg": "#89DDFF"},
        {"name": "Operator", "scope": ["keyword.operator"], "fg": "#89DDFF"},
        {"name": "Decorator", "scope": ["meta.decorator"], "fg": "#E0AF68"},
        {"name": "JSON Key", "scope": ["meta.object-literal.key"], "fg": "#7AA2F7"},
        {"name": "CSS Property", "scope": ["support.type.property-name.css"], "fg": "#7AA2F7"},
        {"name": "CSS Value", "scope": ["support.constant.property-value.css"], "fg": "#9ECE6A"},
        {"name": "HTML Tag", "scope": ["entity.name.tag.html"], "fg": "#F7768E"},
        {"name": "Markdown Heading", "scope": ["markup.heading"], "fg": "#7AA2F7", "style": "bold"},
        {"name": "Markdown Bold", "scope": ["markup.bold"], "fg": "#C0CAF5", "style": "bold"},
        {"name": "Markdown Italic", "scope": ["markup.italic"], "fg": "#E0AF68", "style": "italic"},
        {"name": "Markdown Link", "scope": ["markup.underline.link"], "fg": "#7AA2F7"},
        {"name": "Markdown Code", "scope": ["markup.raw.code"], "fg": "#9ECE6A"},
        {"name": "Regex", "scope": ["string.regexp"], "fg": "#B4F9F8"},
        {"name": "Invalid", "scope": ["invalid"], "fg": "#F7768E", "style": "underline"},
        {"name": "Diff Added", "scope": ["markup.inserted", "diff.inserted"], "fg": "#9ECE6A"},
        {"name": "Diff Deleted", "scope": ["markup.deleted", "diff.deleted"], "fg": "#F7768E"},
        {"name": "Diff Modified", "scope": ["markup.changed", "diff.changed"], "fg": "#E0AF68"},
    ]
}

# ----------------------------------------------------------
# 3. Catppuccin Mocha
# ----------------------------------------------------------
THEMES["catppuccin-mocha"] = {
    "name": "Catppuccin Mocha",
    "type": "dark",
    "colors": {
        "editor.background": "#1E1E2E", "editor.foreground": "#CDD6F4",
        "editorLineNumber.foreground": "#7F849C", "editorLineNumber.activeForeground": "#BAC2DE",
        "editor.selectionBackground": "#585B70", "editor.selectionHighlightBackground": "#585B7080",
        "editor.findMatchBackground": "#F9E2AF80", "editor.findMatchHighlightBackground": "#F9E2AF40",
        "editorCursor.foreground": "#F5E0DC", "editor.lineHighlightBackground": "#31324440",
        "editorIndentGuide.background": "#45475A", "editorIndentGuide.activeBackground": "#585B70",
        "editorBracketMatch.border": "#89B4FA80", "editorGutter.background": "#1E1E2E",
        "editorWidget.background": "#181825", "editorWidget.border": "#313244",
        "editorSuggestWidget.background": "#181825", "editorSuggestWidget.border": "#313244",
        "editorSuggestWidget.selectedBackground": "#313244",
        "editorHoverWidget.background": "#181825", "editorHoverWidget.border": "#313244",
        "editorGroup.border": "#313244", "editorGroupHeader.tabsBackground": "#181825",
        "tab.activeBackground": "#1E1E2E", "tab.activeForeground": "#CDD6F4",
        "tab.inactiveBackground": "#181825", "tab.inactiveForeground": "#6C7086",
        "tab.border": "#313244", "tab.activeBorderTop": "#89B4FA",
        "sideBar.background": "#181825", "sideBar.foreground": "#BAC2DE",
        "sideBar.border": "#313244", "sideBarTitle.foreground": "#CDD6F4",
        "sideBarSectionHeader.background": "#1E1E2E",
        "list.activeSelectionBackground": "#313244", "list.activeSelectionForeground": "#CDD6F4",
        "list.inactiveSelectionBackground": "#31324480", "list.hoverBackground": "#31324440",
        "list.foreground": "#BAC2DE",
        "activityBar.background": "#11111B", "activityBar.foreground": "#89B4FA",
        "activityBar.activeBorder": "#89B4FA", "activityBarBadge.background": "#89B4FA",
        "activityBarBadge.foreground": "#11111B",
        "statusBar.background": "#11111B", "statusBar.foreground": "#CDD6F4",
        "statusBar.debuggingBackground": "#F38BA8",
        "titleBar.activeBackground": "#181825", "titleBar.activeForeground": "#CDD6F4",
        "menu.background": "#181825", "menu.foreground": "#CDD6F4",
        "menu.selectionBackground": "#313244", "menu.separatorBackground": "#313244",
        "button.background": "#89B4FA", "button.foreground": "#11111B",
        "button.hoverBackground": "#B4BEFE",
        "input.background": "#181825", "input.border": "#313244", "input.foreground": "#CDD6F4",
        "dropdown.background": "#181825", "dropdown.border": "#313244",
        "scrollbarSlider.background": "#45475A40", "scrollbarSlider.hoverBackground": "#45475A60",
        "panel.background": "#181825", "panel.border": "#313244",
        "terminal.background": "#1E1E2E", "terminal.foreground": "#CDD6F4",
        "gitDecoration.addedResourceForeground": "#A6E3A1",
        "gitDecoration.modifiedResourceForeground": "#F9E2AF",
        "gitDecoration.deletedResourceForeground": "#F38BA8",
        "gitDecoration.untrackedResourceForeground": "#A6E3A1",
        "gitDecoration.ignoredResourceForeground": "#6C7086",
        "gitDecoration.conflictResourceForeground": "#FAB387",
        "badge.background": "#89B4FA", "badge.foreground": "#11111B",
        "progressBar.background": "#89B4FA", "focusBorder": "#89B4FA80",
        "foreground": "#CDD6F4", "errorForeground": "#F38BA8",
        "textLink.foreground": "#89B4FA", "icon.foreground": "#6C7086",
        "widget.shadow": "#00000060",
    },
    "tokens": [
        {"name": "Comment", "scope": ["comment"], "fg": "#6C7086", "style": "italic"},
        {"name": "String", "scope": ["string"], "fg": "#A6E3A1"},
        {"name": "Number", "scope": ["constant.numeric"], "fg": "#FAB387"},
        {"name": "Boolean/Null", "scope": ["constant.language.boolean", "constant.language.null"], "fg": "#FAB387"},
        {"name": "Keyword", "scope": ["keyword", "keyword.control"], "fg": "#CBA6F7"},
        {"name": "Storage/Modifier", "scope": ["storage", "storage.type"], "fg": "#CBA6F7"},
        {"name": "Function", "scope": ["entity.name.function", "support.function"], "fg": "#89B4FA"},
        {"name": "Class/Type", "scope": ["entity.name.type", "entity.name.class", "support.type"], "fg": "#89DCEB"},
        {"name": "Variable", "scope": ["variable"], "fg": "#CDD6F4"},
        {"name": "Parameter", "scope": ["variable.parameter"], "fg": "#EBA0AC"},
        {"name": "Property", "scope": ["variable.other.property"], "fg": "#94E2D5"},
        {"name": "Constant", "scope": ["variable.other.constant"], "fg": "#FAB387"},
        {"name": "Tag", "scope": ["entity.name.tag"], "fg": "#F38BA8"},
        {"name": "Attribute", "scope": ["entity.other.attribute-name"], "fg": "#F9E2AF"},
        {"name": "Punctuation", "scope": ["punctuation", "meta.brace"], "fg": "#9399B2"},
        {"name": "Operator", "scope": ["keyword.operator"], "fg": "#94E2D5"},
        {"name": "Decorator", "scope": ["meta.decorator"], "fg": "#F9E2AF"},
        {"name": "JSON Key", "scope": ["meta.object-literal.key"], "fg": "#89B4FA"},
        {"name": "CSS Property", "scope": ["support.type.property-name.css"], "fg": "#94E2D5"},
        {"name": "CSS Value", "scope": ["support.constant.property-value.css"], "fg": "#A6E3A1"},
        {"name": "HTML Tag", "scope": ["entity.name.tag.html"], "fg": "#F38BA8"},
        {"name": "Markdown Heading", "scope": ["markup.heading"], "fg": "#CBA6F7", "style": "bold"},
        {"name": "Markdown Bold", "scope": ["markup.bold"], "fg": "#CDD6F4", "style": "bold"},
        {"name": "Markdown Italic", "scope": ["markup.italic"], "fg": "#EBA0AC", "style": "italic"},
        {"name": "Markdown Link", "scope": ["markup.underline.link"], "fg": "#89B4FA"},
        {"name": "Markdown Code", "scope": ["markup.raw.code"], "fg": "#A6E3A1"},
        {"name": "Regex", "scope": ["string.regexp"], "fg": "#F5C2E7"},
        {"name": "Invalid", "scope": ["invalid"], "fg": "#F38BA8", "style": "underline"},
        {"name": "Diff Added", "scope": ["markup.inserted", "diff.inserted"], "fg": "#A6E3A1"},
        {"name": "Diff Deleted", "scope": ["markup.deleted", "diff.deleted"], "fg": "#F38BA8"},
        {"name": "Diff Modified", "scope": ["markup.changed", "diff.changed"], "fg": "#F9E2AF"},
    ]
}

# ----------------------------------------------------------
# 4. Nord
# ----------------------------------------------------------
THEMES["nord"] = {
    "name": "Nord",
    "type": "dark",
    "colors": {
        "editor.background": "#2E3440", "editor.foreground": "#D8DEE9",
        "editorLineNumber.foreground": "#4C566A", "editorLineNumber.activeForeground": "#88C0D0",
        "editor.selectionBackground": "#434C5E", "editor.selectionHighlightBackground": "#434C5E80",
        "editor.findMatchBackground": "#88C0D080", "editor.findMatchHighlightBackground": "#88C0D040",
        "editorCursor.foreground": "#D8DEE9", "editor.lineHighlightBackground": "#3B4252",
        "editorIndentGuide.background": "#434C5E", "editorIndentGuide.activeBackground": "#4C566A",
        "editorBracketMatch.border": "#88C0D080", "editorGutter.background": "#2E3440",
        "editorWidget.background": "#2E3440", "editorWidget.border": "#3B4252",
        "editorSuggestWidget.background": "#2E3440", "editorSuggestWidget.border": "#3B4252",
        "editorSuggestWidget.selectedBackground": "#434C5E",
        "editorHoverWidget.background": "#2E3440", "editorHoverWidget.border": "#3B4252",
        "editorGroup.border": "#3B4252", "editorGroupHeader.tabsBackground": "#2E3440",
        "tab.activeBackground": "#2E3440", "tab.activeForeground": "#D8DEE9",
        "tab.inactiveBackground": "#2E3440", "tab.inactiveForeground": "#4C566A",
        "tab.border": "#3B4252", "tab.activeBorderTop": "#88C0D0",
        "sideBar.background": "#2E3440", "sideBar.foreground": "#D8DEE9",
        "sideBar.border": "#3B4252", "sideBarTitle.foreground": "#E5E9F0",
        "sideBarSectionHeader.background": "#3B4252",
        "list.activeSelectionBackground": "#434C5E", "list.activeSelectionForeground": "#E5E9F0",
        "list.inactiveSelectionBackground": "#434C5E80", "list.hoverBackground": "#3B4252",
        "list.foreground": "#D8DEE9",
        "activityBar.background": "#2E3440", "activityBar.foreground": "#D8DEE9",
        "activityBar.activeBorder": "#88C0D0", "activityBarBadge.background": "#88C0D0",
        "activityBarBadge.foreground": "#2E3440",
        "statusBar.background": "#3B4252", "statusBar.foreground": "#E5E9F0",
        "statusBar.debuggingBackground": "#BF616A",
        "titleBar.activeBackground": "#2E3440", "titleBar.activeForeground": "#E5E9F0",
        "menu.background": "#3B4252", "menu.foreground": "#D8DEE9",
        "menu.selectionBackground": "#434C5E", "menu.separatorBackground": "#434C5E",
        "button.background": "#88C0D0", "button.foreground": "#2E3440",
        "button.hoverBackground": "#8FBCBB",
        "input.background": "#3B4252", "input.border": "#434C5E", "input.foreground": "#E5E9F0",
        "dropdown.background": "#3B4252", "dropdown.border": "#434C5E",
        "scrollbarSlider.background": "#4C566A40", "scrollbarSlider.hoverBackground": "#4C566A60",
        "panel.background": "#2E3440", "panel.border": "#3B4252",
        "terminal.background": "#2E3440", "terminal.foreground": "#D8DEE9",
        "gitDecoration.addedResourceForeground": "#A3BE8C",
        "gitDecoration.modifiedResourceForeground": "#EBCB8B",
        "gitDecoration.deletedResourceForeground": "#BF616A",
        "gitDecoration.untrackedResourceForeground": "#A3BE8C",
        "gitDecoration.ignoredResourceForeground": "#4C566A",
        "gitDecoration.conflictResourceForeground": "#D08770",
        "badge.background": "#88C0D0", "badge.foreground": "#2E3440",
        "progressBar.background": "#88C0D0", "focusBorder": "#88C0D080",
        "foreground": "#D8DEE9", "errorForeground": "#BF616A",
        "textLink.foreground": "#88C0D0", "icon.foreground": "#4C566A",
        "widget.shadow": "#00000060",
    },
    "tokens": [
        {"name": "Comment", "scope": ["comment"], "fg": "#616E88", "style": "italic"},
        {"name": "String", "scope": ["string"], "fg": "#A3BE8C"},
        {"name": "Number", "scope": ["constant.numeric"], "fg": "#B48EAD"},
        {"name": "Boolean/Null", "scope": ["constant.language.boolean", "constant.language.null"], "fg": "#B48EAD"},
        {"name": "Keyword", "scope": ["keyword", "keyword.control"], "fg": "#81A1C1"},
        {"name": "Storage/Modifier", "scope": ["storage", "storage.type"], "fg": "#81A1C1"},
        {"name": "Function", "scope": ["entity.name.function", "support.function"], "fg": "#88C0D0"},
        {"name": "Class/Type", "scope": ["entity.name.type", "entity.name.class", "support.type"], "fg": "#8FBCBB"},
        {"name": "Variable", "scope": ["variable"], "fg": "#D8DEE9"},
        {"name": "Parameter", "scope": ["variable.parameter"], "fg": "#EBCB8B"},
        {"name": "Property", "scope": ["variable.other.property"], "fg": "#81A1C1"},
        {"name": "Constant", "scope": ["variable.other.constant"], "fg": "#D08770"},
        {"name": "Tag", "scope": ["entity.name.tag"], "fg": "#81A1C1"},
        {"name": "Attribute", "scope": ["entity.other.attribute-name"], "fg": "#8FBCBB"},
        {"name": "Punctuation", "scope": ["punctuation", "meta.brace"], "fg": "#81A1C1"},
        {"name": "Operator", "scope": ["keyword.operator"], "fg": "#81A1C1"},
        {"name": "Decorator", "scope": ["meta.decorator"], "fg": "#8FBCBB"},
        {"name": "JSON Key", "scope": ["meta.object-literal.key"], "fg": "#81A1C1"},
        {"name": "CSS Property", "scope": ["support.type.property-name.css"], "fg": "#81A1C1"},
        {"name": "CSS Value", "scope": ["support.constant.property-value.css"], "fg": "#A3BE8C"},
        {"name": "HTML Tag", "scope": ["entity.name.tag.html"], "fg": "#81A1C1"},
        {"name": "Markdown Heading", "scope": ["markup.heading"], "fg": "#88C0D0", "style": "bold"},
        {"name": "Markdown Bold", "scope": ["markup.bold"], "fg": "#E5E9F0", "style": "bold"},
        {"name": "Markdown Italic", "scope": ["markup.italic"], "fg": "#EBCB8B", "style": "italic"},
        {"name": "Markdown Link", "scope": ["markup.underline.link"], "fg": "#88C0D0"},
        {"name": "Markdown Code", "scope": ["markup.raw.code"], "fg": "#A3BE8C"},
        {"name": "Regex", "scope": ["string.regexp"], "fg": "#A3BE8C"},
        {"name": "Invalid", "scope": ["invalid"], "fg": "#BF616A", "style": "underline"},
        {"name": "Diff Added", "scope": ["markup.inserted", "diff.inserted"], "fg": "#A3BE8C"},
        {"name": "Diff Deleted", "scope": ["markup.deleted", "diff.deleted"], "fg": "#BF616A"},
        {"name": "Diff Modified", "scope": ["markup.changed", "diff.changed"], "fg": "#EBCB8B"},
    ]
}

# ----------------------------------------------------------
# 5. Solarized Dark
# ----------------------------------------------------------
THEMES["solarized-dark"] = {
    "name": "Solarized Dark",
    "type": "dark",
    "colors": {
        "editor.background": "#002B36", "editor.foreground": "#93A1A1",
        "editorLineNumber.foreground": "#586E75", "editorLineNumber.activeForeground": "#93A1A1",
        "editor.selectionBackground": "#073642", "editor.selectionHighlightBackground": "#07364280",
        "editor.findMatchBackground": "#B5895080", "editor.findMatchHighlightBackground": "#B5895040",
        "editorCursor.foreground": "#839496", "editor.lineHighlightBackground": "#073642",
        "editorIndentGuide.background": "#586E7540", "editorIndentGuide.activeBackground": "#586E75",
        "editorBracketMatch.border": "#268BD280", "editorGutter.background": "#002B36",
        "editorWidget.background": "#073642", "editorWidget.border": "#586E75",
        "editorSuggestWidget.background": "#073642", "editorSuggestWidget.border": "#586E75",
        "editorSuggestWidget.selectedBackground": "#073642",
        "editorHoverWidget.background": "#073642", "editorHoverWidget.border": "#586E75",
        "editorGroup.border": "#586E75", "editorGroupHeader.tabsBackground": "#002B36",
        "tab.activeBackground": "#002B36", "tab.activeForeground": "#93A1A1",
        "tab.inactiveBackground": "#073642", "tab.inactiveForeground": "#586E75",
        "tab.border": "#586E75", "tab.activeBorderTop": "#268BD2",
        "sideBar.background": "#073642", "sideBar.foreground": "#93A1A1",
        "sideBar.border": "#586E75", "sideBarTitle.foreground": "#93A1A1",
        "sideBarSectionHeader.background": "#002B36",
        "list.activeSelectionBackground": "#073642", "list.activeSelectionForeground": "#93A1A1",
        "list.inactiveSelectionBackground": "#07364280", "list.hoverBackground": "#073642",
        "list.foreground": "#93A1A1",
        "activityBar.background": "#002B36", "activityBar.foreground": "#93A1A1",
        "activityBar.activeBorder": "#268BD2", "activityBarBadge.background": "#268BD2",
        "activityBarBadge.foreground": "#002B36",
        "statusBar.background": "#002B36", "statusBar.foreground": "#93A1A1",
        "statusBar.debuggingBackground": "#CB4B16",
        "titleBar.activeBackground": "#073642", "titleBar.activeForeground": "#93A1A1",
        "menu.background": "#073642", "menu.foreground": "#93A1A1",
        "menu.selectionBackground": "#586E75", "menu.separatorBackground": "#586E75",
        "button.background": "#268BD2", "button.foreground": "#002B36",
        "button.hoverBackground": "#3AA3E3",
        "input.background": "#073642", "input.border": "#586E75", "input.foreground": "#93A1A1",
        "dropdown.background": "#073642", "dropdown.border": "#586E75",
        "scrollbarSlider.background": "#586E7540", "scrollbarSlider.hoverBackground": "#586E7560",
        "panel.background": "#073642", "panel.border": "#586E75",
        "terminal.background": "#002B36", "terminal.foreground": "#93A1A1",
        "gitDecoration.addedResourceForeground": "#859900",
        "gitDecoration.modifiedResourceForeground": "#B58900",
        "gitDecoration.deletedResourceForeground": "#DC322F",
        "gitDecoration.untrackedResourceForeground": "#859900",
        "gitDecoration.ignoredResourceForeground": "#586E75",
        "gitDecoration.conflictResourceForeground": "#CB4B16",
        "badge.background": "#268BD2", "badge.foreground": "#002B36",
        "progressBar.background": "#268BD2", "focusBorder": "#268BD280",
        "foreground": "#93A1A1", "errorForeground": "#DC322F",
        "textLink.foreground": "#268BD2", "icon.foreground": "#586E75",
        "widget.shadow": "#00000060",
    },
    "tokens": [
        {"name": "Comment", "scope": ["comment"], "fg": "#586E75", "style": "italic"},
        {"name": "String", "scope": ["string"], "fg": "#2AA198"},
        {"name": "Number", "scope": ["constant.numeric"], "fg": "#D33682"},
        {"name": "Boolean/Null", "scope": ["constant.language.boolean", "constant.language.null"], "fg": "#D33682"},
        {"name": "Keyword", "scope": ["keyword", "keyword.control"], "fg": "#859900"},
        {"name": "Storage/Modifier", "scope": ["storage", "storage.type"], "fg": "#859900"},
        {"name": "Function", "scope": ["entity.name.function", "support.function"], "fg": "#268BD2"},
        {"name": "Class/Type", "scope": ["entity.name.type", "entity.name.class", "support.type"], "fg": "#B58900"},
        {"name": "Variable", "scope": ["variable"], "fg": "#839496"},
        {"name": "Parameter", "scope": ["variable.parameter"], "fg": "#B58900"},
        {"name": "Property", "scope": ["variable.other.property"], "fg": "#93A1A1"},
        {"name": "Constant", "scope": ["variable.other.constant"], "fg": "#D33682"},
        {"name": "Tag", "scope": ["entity.name.tag"], "fg": "#268BD2"},
        {"name": "Attribute", "scope": ["entity.other.attribute-name"], "fg": "#93A1A1"},
        {"name": "Punctuation", "scope": ["punctuation", "meta.brace"], "fg": "#586E75"},
        {"name": "Operator", "scope": ["keyword.operator"], "fg": "#859900"},
        {"name": "Decorator", "scope": ["meta.decorator"], "fg": "#B58900"},
        {"name": "JSON Key", "scope": ["meta.object-literal.key"], "fg": "#93A1A1"},
        {"name": "CSS Property", "scope": ["support.type.property-name.css"], "fg": "#268BD2"},
        {"name": "CSS Value", "scope": ["support.constant.property-value.css"], "fg": "#2AA198"},
        {"name": "HTML Tag", "scope": ["entity.name.tag.html"], "fg": "#268BD2"},
        {"name": "Markdown Heading", "scope": ["markup.heading"], "fg": "#B58900", "style": "bold"},
        {"name": "Markdown Bold", "scope": ["markup.bold"], "fg": "#839496", "style": "bold"},
        {"name": "Markdown Italic", "scope": ["markup.italic"], "fg": "#B58900", "style": "italic"},
        {"name": "Markdown Link", "scope": ["markup.underline.link"], "fg": "#268BD2"},
        {"name": "Markdown Code", "scope": ["markup.raw.code"], "fg": "#2AA198"},
        {"name": "Regex", "scope": ["string.regexp"], "fg": "#2AA198"},
        {"name": "Invalid", "scope": ["invalid"], "fg": "#DC322F", "style": "underline"},
        {"name": "Diff Added", "scope": ["markup.inserted", "diff.inserted"], "fg": "#859900"},
        {"name": "Diff Deleted", "scope": ["markup.deleted", "diff.deleted"], "fg": "#DC322F"},
        {"name": "Diff Modified", "scope": ["markup.changed", "diff.changed"], "fg": "#B58900"},
    ]
}

# ----------------------------------------------------------
# 6. Gruvbox Dark
# ----------------------------------------------------------
THEMES["gruvbox-dark"] = {
    "name": "Gruvbox Dark",
    "type": "dark",
    "colors": {
        "editor.background": "#282828", "editor.foreground": "#EBDBB2",
        "editorLineNumber.foreground": "#7C6F64", "editorLineNumber.activeForeground": "#FABD2F",
        "editor.selectionBackground": "#3C3836", "editor.selectionHighlightBackground": "#3C383680",
        "editor.findMatchBackground": "#FABD2F80", "editor.findMatchHighlightBackground": "#FABD2F40",
        "editorCursor.foreground": "#EBDBB2", "editor.lineHighlightBackground": "#3C3836",
        "editorIndentGuide.background": "#504945", "editorIndentGuide.activeBackground": "#7C6F64",
        "editorBracketMatch.border": "#FABD2F80", "editorGutter.background": "#282828",
        "editorWidget.background": "#1D2021", "editorWidget.border": "#3C3836",
        "editorSuggestWidget.background": "#1D2021", "editorSuggestWidget.border": "#3C3836",
        "editorSuggestWidget.selectedBackground": "#3C3836",
        "editorHoverWidget.background": "#1D2021", "editorHoverWidget.border": "#3C3836",
        "editorGroup.border": "#3C3836", "editorGroupHeader.tabsBackground": "#1D2021",
        "tab.activeBackground": "#282828", "tab.activeForeground": "#EBDBB2",
        "tab.inactiveBackground": "#1D2021", "tab.inactiveForeground": "#7C6F64",
        "tab.border": "#3C3836", "tab.activeBorderTop": "#FABD2F",
        "sideBar.background": "#1D2021", "sideBar.foreground": "#A89984",
        "sideBar.border": "#3C3836", "sideBarTitle.foreground": "#EBDBB2",
        "sideBarSectionHeader.background": "#282828",
        "list.activeSelectionBackground": "#3C3836", "list.activeSelectionForeground": "#EBDBB2",
        "list.inactiveSelectionBackground": "#3C383680", "list.hoverBackground": "#3C3836",
        "list.foreground": "#A89984",
        "activityBar.background": "#1D2021", "activityBar.foreground": "#A89984",
        "activityBar.activeBorder": "#FABD2F", "activityBarBadge.background": "#FABD2F",
        "activityBarBadge.foreground": "#1D2021",
        "statusBar.background": "#1D2021", "statusBar.foreground": "#EBDBB2",
        "statusBar.debuggingBackground": "#FB4934",
        "titleBar.activeBackground": "#1D2021", "titleBar.activeForeground": "#EBDBB2",
        "menu.background": "#1D2021", "menu.foreground": "#EBDBB2",
        "menu.selectionBackground": "#3C3836", "menu.separatorBackground": "#3C3836",
        "button.background": "#FABD2F", "button.foreground": "#1D2021",
        "button.hoverBackground": "#FCC424",
        "input.background": "#1D2021", "input.border": "#3C3836", "input.foreground": "#EBDBB2",
        "dropdown.background": "#1D2021", "dropdown.border": "#3C3836",
        "scrollbarSlider.background": "#50494540", "scrollbarSlider.hoverBackground": "#50494560",
        "panel.background": "#1D2021", "panel.border": "#3C3836",
        "terminal.background": "#282828", "terminal.foreground": "#EBDBB2",
        "gitDecoration.addedResourceForeground": "#B8BB26",
        "gitDecoration.modifiedResourceForeground": "#FABD2F",
        "gitDecoration.deletedResourceForeground": "#FB4934",
        "gitDecoration.untrackedResourceForeground": "#B8BB26",
        "gitDecoration.ignoredResourceForeground": "#7C6F64",
        "gitDecoration.conflictResourceForeground": "#FE8019",
        "badge.background": "#FABD2F", "badge.foreground": "#1D2021",
        "progressBar.background": "#FABD2F", "focusBorder": "#FABD2F80",
        "foreground": "#EBDBB2", "errorForeground": "#FB4934",
        "textLink.foreground": "#83A598", "icon.foreground": "#7C6F64",
        "widget.shadow": "#00000060",
    },
    "tokens": [
        {"name": "Comment", "scope": ["comment"], "fg": "#928374", "style": "italic"},
        {"name": "String", "scope": ["string"], "fg": "#B8BB26"},
        {"name": "Number", "scope": ["constant.numeric"], "fg": "#D3869B"},
        {"name": "Boolean/Null", "scope": ["constant.language.boolean", "constant.language.null"], "fg": "#D3869B"},
        {"name": "Keyword", "scope": ["keyword", "keyword.control"], "fg": "#FB4934"},
        {"name": "Storage/Modifier", "scope": ["storage", "storage.type"], "fg": "#FB4934"},
        {"name": "Function", "scope": ["entity.name.function", "support.function"], "fg": "#FABD2F"},
        {"name": "Class/Type", "scope": ["entity.name.type", "entity.name.class", "support.type"], "fg": "#FABD2F"},
        {"name": "Variable", "scope": ["variable"], "fg": "#EBDBB2"},
        {"name": "Parameter", "scope": ["variable.parameter"], "fg": "#FE8019"},
        {"name": "Property", "scope": ["variable.other.property"], "fg": "#A89984"},
        {"name": "Constant", "scope": ["variable.other.constant"], "fg": "#D3869B"},
        {"name": "Tag", "scope": ["entity.name.tag"], "fg": "#FB4934"},
        {"name": "Attribute", "scope": ["entity.other.attribute-name"], "fg": "#FABD2F"},
        {"name": "Punctuation", "scope": ["punctuation", "meta.brace"], "fg": "#A89984"},
        {"name": "Operator", "scope": ["keyword.operator"], "fg": "#83A598"},
        {"name": "Decorator", "scope": ["meta.decorator"], "fg": "#FABD2F"},
        {"name": "JSON Key", "scope": ["meta.object-literal.key"], "fg": "#A89984"},
        {"name": "CSS Property", "scope": ["support.type.property-name.css"], "fg": "#FABD2F"},
        {"name": "CSS Value", "scope": ["support.constant.property-value.css"], "fg": "#B8BB26"},
        {"name": "HTML Tag", "scope": ["entity.name.tag.html"], "fg": "#FB4934"},
        {"name": "Markdown Heading", "scope": ["markup.heading"], "fg": "#FABD2F", "style": "bold"},
        {"name": "Markdown Bold", "scope": ["markup.bold"], "fg": "#EBDBB2", "style": "bold"},
        {"name": "Markdown Italic", "scope": ["markup.italic"], "fg": "#FE8019", "style": "italic"},
        {"name": "Markdown Link", "scope": ["markup.underline.link"], "fg": "#83A598"},
        {"name": "Markdown Code", "scope": ["markup.raw.code"], "fg": "#B8BB26"},
        {"name": "Regex", "scope": ["string.regexp"], "fg": "#B8BB26"},
        {"name": "Invalid", "scope": ["invalid"], "fg": "#FB4934", "style": "underline"},
        {"name": "Diff Added", "scope": ["markup.inserted", "diff.inserted"], "fg": "#B8BB26"},
        {"name": "Diff Deleted", "scope": ["markup.deleted", "diff.deleted"], "fg": "#FB4934"},
        {"name": "Diff Modified", "scope": ["markup.changed", "diff.changed"], "fg": "#FABD2F"},
    ]
}

# ----------------------------------------------------------
# 7. Synthwave '84
# ----------------------------------------------------------
THEMES["synthwave-84"] = {
    "name": "Synthwave 84",
    "type": "dark",
    "colors": {
        "editor.background": "#262335", "editor.foreground": "#CAC8C5",
        "editorLineNumber.foreground": "#4A4A6A", "editorLineNumber.activeForeground": "#FF7EDB",
        "editor.selectionBackground": "#495495", "editor.selectionHighlightBackground": "#49549580",
        "editor.findMatchBackground": "#FF7EDB80", "editor.findMatchHighlightBackground": "#FF7EDB40",
        "editorCursor.foreground": "#F92AAD", "editor.lineHighlightBackground": "#34294F",
        "editorIndentGuide.background": "#49549540", "editorIndentGuide.activeBackground": "#495495",
        "editorBracketMatch.border": "#FF7EDB80", "editorGutter.background": "#262335",
        "editorWidget.background": "#1A1721", "editorWidget.border": "#495495",
        "editorSuggestWidget.background": "#1A1721", "editorSuggestWidget.border": "#495495",
        "editorSuggestWidget.selectedBackground": "#495495",
        "editorHoverWidget.background": "#1A1721", "editorHoverWidget.border": "#495495",
        "editorGroup.border": "#495495", "editorGroupHeader.tabsBackground": "#1A1721",
        "tab.activeBackground": "#262335", "tab.activeForeground": "#CAC8C5",
        "tab.inactiveBackground": "#1A1721", "tab.inactiveForeground": "#4A4A6A",
        "tab.border": "#495495", "tab.activeBorderTop": "#FF7EDB",
        "sideBar.background": "#1A1721", "sideBar.foreground": "#CAC8C5",
        "sideBar.border": "#495495", "sideBarTitle.foreground": "#FF7EDB",
        "sideBarSectionHeader.background": "#262335",
        "list.activeSelectionBackground": "#495495", "list.activeSelectionForeground": "#CAC8C5",
        "list.inactiveSelectionBackground": "#49549580", "list.hoverBackground": "#34294F",
        "list.foreground": "#CAC8C5",
        "activityBar.background": "#1A1721", "activityBar.foreground": "#CAC8C5",
        "activityBar.activeBorder": "#FF7EDB", "activityBarBadge.background": "#FF7EDB",
        "activityBarBadge.foreground": "#1A1721",
        "statusBar.background": "#1A1721", "statusBar.foreground": "#CAC8C5",
        "statusBar.debuggingBackground": "#F92AAD",
        "titleBar.activeBackground": "#1A1721", "titleBar.activeForeground": "#CAC8C5",
        "menu.background": "#1A1721", "menu.foreground": "#CAC8C5",
        "menu.selectionBackground": "#495495", "menu.separatorBackground": "#495495",
        "button.background": "#FF7EDB", "button.foreground": "#1A1721",
        "button.hoverBackground": "#FF96E8",
        "input.background": "#1A1721", "input.border": "#495495", "input.foreground": "#CAC8C5",
        "dropdown.background": "#1A1721", "dropdown.border": "#495495",
        "scrollbarSlider.background": "#4A4A6A40", "scrollbarSlider.hoverBackground": "#4A4A6A60",
        "panel.background": "#1A1721", "panel.border": "#495495",
        "terminal.background": "#262335", "terminal.foreground": "#CAC8C5",
        "gitDecoration.addedResourceForeground": "#72F1B8",
        "gitDecoration.modifiedResourceForeground": "#F92AAD",
        "gitDecoration.deletedResourceForeground": "#FF7EDB",
        "gitDecoration.untrackedResourceForeground": "#72F1B8",
        "gitDecoration.ignoredResourceForeground": "#4A4A6A",
        "gitDecoration.conflictResourceForeground": "#FFB86C",
        "badge.background": "#FF7EDB", "badge.foreground": "#1A1721",
        "progressBar.background": "#FF7EDB", "focusBorder": "#FF7EDB80",
        "foreground": "#CAC8C5", "errorForeground": "#FF7EDB",
        "textLink.foreground": "#72F1B8", "icon.foreground": "#4A4A6A",
        "widget.shadow": "#00000080",
    },
    "tokens": [
        {"name": "Comment", "scope": ["comment"], "fg": "#6D679E", "style": "italic"},
        {"name": "String", "scope": ["string"], "fg": "#72F1B8"},
        {"name": "Number", "scope": ["constant.numeric"], "fg": "#FFB86C"},
        {"name": "Boolean/Null", "scope": ["constant.language.boolean", "constant.language.null"], "fg": "#FFB86C"},
        {"name": "Keyword", "scope": ["keyword", "keyword.control"], "fg": "#F92AAD"},
        {"name": "Storage/Modifier", "scope": ["storage", "storage.type"], "fg": "#F92AAD"},
        {"name": "Function", "scope": ["entity.name.function", "support.function"], "fg": "#72F1B8"},
        {"name": "Class/Type", "scope": ["entity.name.type", "entity.name.class", "support.type"], "fg": "#FFB86C"},
        {"name": "Variable", "scope": ["variable"], "fg": "#CAC8C5"},
        {"name": "Parameter", "scope": ["variable.parameter"], "fg": "#FF7EDB"},
        {"name": "Property", "scope": ["variable.other.property"], "fg": "#FF7EDB"},
        {"name": "Constant", "scope": ["variable.other.constant"], "fg": "#FFB86C"},
        {"name": "Tag", "scope": ["entity.name.tag"], "fg": "#F92AAD"},
        {"name": "Attribute", "scope": ["entity.other.attribute-name"], "fg": "#72F1B8"},
        {"name": "Punctuation", "scope": ["punctuation", "meta.brace"], "fg": "#8480BB"},
        {"name": "Operator", "scope": ["keyword.operator"], "fg": "#F92AAD"},
        {"name": "Decorator", "scope": ["meta.decorator"], "fg": "#72F1B8"},
        {"name": "JSON Key", "scope": ["meta.object-literal.key"], "fg": "#FF7EDB"},
        {"name": "CSS Property", "scope": ["support.type.property-name.css"], "fg": "#FF7EDB"},
        {"name": "CSS Value", "scope": ["support.constant.property-value.css"], "fg": "#72F1B8"},
        {"name": "HTML Tag", "scope": ["entity.name.tag.html"], "fg": "#F92AAD"},
        {"name": "Markdown Heading", "scope": ["markup.heading"], "fg": "#FFB86C", "style": "bold"},
        {"name": "Markdown Bold", "scope": ["markup.bold"], "fg": "#F92AAD", "style": "bold"},
        {"name": "Markdown Italic", "scope": ["markup.italic"], "fg": "#FF7EDB", "style": "italic"},
        {"name": "Markdown Link", "scope": ["markup.underline.link"], "fg": "#72F1B8"},
        {"name": "Markdown Code", "scope": ["markup.raw.code"], "fg": "#72F1B8"},
        {"name": "Regex", "scope": ["string.regexp"], "fg": "#72F1B8"},
        {"name": "Invalid", "scope": ["invalid"], "fg": "#FF7EDB", "style": "underline"},
        {"name": "Diff Added", "scope": ["markup.inserted", "diff.inserted"], "fg": "#72F1B8"},
        {"name": "Diff Deleted", "scope": ["markup.deleted", "diff.deleted"], "fg": "#FF7EDB"},
        {"name": "Diff Modified", "scope": ["markup.changed", "diff.changed"], "fg": "#FFB86C"},
    ]
}

# ----------------------------------------------------------
# 8. Everforest Dark
# ----------------------------------------------------------
THEMES["everforest-dark"] = {
    "name": "Everforest Dark",
    "type": "dark",
    "colors": {
        "editor.background": "#2D353B", "editor.foreground": "#D3C6AA",
        "editorLineNumber.foreground": "#475258", "editorLineNumber.activeForeground": "#A7C080",
        "editor.selectionBackground": "#3D484D", "editor.selectionHighlightBackground": "#3D484D80",
        "editor.findMatchBackground": "#E6987580", "editor.findMatchHighlightBackground": "#E6987540",
        "editorCursor.foreground": "#D3C6AA", "editor.lineHighlightBackground": "#343F44",
        "editorIndentGuide.background": "#475258", "editorIndentGuide.activeBackground": "#859289",
        "editorBracketMatch.border": "#A7C08080", "editorGutter.background": "#2D353B",
        "editorWidget.background": "#232A2E", "editorWidget.border": "#475258",
        "editorSuggestWidget.background": "#232A2E", "editorSuggestWidget.border": "#475258",
        "editorSuggestWidget.selectedBackground": "#3D484D",
        "editorHoverWidget.background": "#232A2E", "editorHoverWidget.border": "#475258",
        "editorGroup.border": "#475258", "editorGroupHeader.tabsBackground": "#232A2E",
        "tab.activeBackground": "#2D353B", "tab.activeForeground": "#D3C6AA",
        "tab.inactiveBackground": "#232A2E", "tab.inactiveForeground": "#475258",
        "tab.border": "#475258", "tab.activeBorderTop": "#A7C080",
        "sideBar.background": "#232A2E", "sideBar.foreground": "#9DA9A0",
        "sideBar.border": "#475258", "sideBarTitle.foreground": "#D3C6AA",
        "sideBarSectionHeader.background": "#2D353B",
        "list.activeSelectionBackground": "#3D484D", "list.activeSelectionForeground": "#D3C6AA",
        "list.inactiveSelectionBackground": "#3D484D80", "list.hoverBackground": "#343F44",
        "list.foreground": "#9DA9A0",
        "activityBar.background": "#1E2326", "activityBar.foreground": "#9DA9A0",
        "activityBar.activeBorder": "#A7C080", "activityBarBadge.background": "#A7C080",
        "activityBarBadge.foreground": "#1E2326",
        "statusBar.background": "#1E2326", "statusBar.foreground": "#D3C6AA",
        "statusBar.debuggingBackground": "#E67E80",
        "titleBar.activeBackground": "#232A2E", "titleBar.activeForeground": "#D3C6AA",
        "menu.background": "#232A2E", "menu.foreground": "#D3C6AA",
        "menu.selectionBackground": "#3D484D", "menu.separatorBackground": "#475258",
        "button.background": "#A7C080", "button.foreground": "#1E2326",
        "button.hoverBackground": "#B7D090",
        "input.background": "#232A2E", "input.border": "#475258", "input.foreground": "#D3C6AA",
        "dropdown.background": "#232A2E", "dropdown.border": "#475258",
        "scrollbarSlider.background": "#47525840", "scrollbarSlider.hoverBackground": "#47525860",
        "panel.background": "#232A2E", "panel.border": "#475258",
        "terminal.background": "#2D353B", "terminal.foreground": "#D3C6AA",
        "gitDecoration.addedResourceForeground": "#A7C080",
        "gitDecoration.modifiedResourceForeground": "#E69875",
        "gitDecoration.deletedResourceForeground": "#E67E80",
        "gitDecoration.untrackedResourceForeground": "#A7C080",
        "gitDecoration.ignoredResourceForeground": "#475258",
        "gitDecoration.conflictResourceForeground": "#DBBC7F",
        "badge.background": "#A7C080", "badge.foreground": "#1E2326",
        "progressBar.background": "#A7C080", "focusBorder": "#A7C08080",
        "foreground": "#D3C6AA", "errorForeground": "#E67E80",
        "textLink.foreground": "#7FBBB3", "icon.foreground": "#475258",
        "widget.shadow": "#00000060",
    },
    "tokens": [
        {"name": "Comment", "scope": ["comment"], "fg": "#7A8478", "style": "italic"},
        {"name": "String", "scope": ["string"], "fg": "#A7C080"},
        {"name": "Number", "scope": ["constant.numeric"], "fg": "#E69875"},
        {"name": "Boolean/Null", "scope": ["constant.language.boolean", "constant.language.null"], "fg": "#E69875"},
        {"name": "Keyword", "scope": ["keyword", "keyword.control"], "fg": "#9DA9A0"},
        {"name": "Storage/Modifier", "scope": ["storage", "storage.type"], "fg": "#9DA9A0"},
        {"name": "Function", "scope": ["entity.name.function", "support.function"], "fg": "#A7C080"},
        {"name": "Class/Type", "scope": ["entity.name.type", "entity.name.class", "support.type"], "fg": "#DBBC7F"},
        {"name": "Variable", "scope": ["variable"], "fg": "#D3C6AA"},
        {"name": "Parameter", "scope": ["variable.parameter"], "fg": "#E69875"},
        {"name": "Property", "scope": ["variable.other.property"], "fg": "#9DA9A0"},
        {"name": "Constant", "scope": ["variable.other.constant"], "fg": "#E69875"},
        {"name": "Tag", "scope": ["entity.name.tag"], "fg": "#9DA9A0"},
        {"name": "Attribute", "scope": ["entity.other.attribute-name"], "fg": "#DBBC7F"},
        {"name": "Punctuation", "scope": ["punctuation", "meta.brace"], "fg": "#859289"},
        {"name": "Operator", "scope": ["keyword.operator"], "fg": "#859289"},
        {"name": "Decorator", "scope": ["meta.decorator"], "fg": "#DBBC7F"},
        {"name": "JSON Key", "scope": ["meta.object-literal.key"], "fg": "#9DA9A0"},
        {"name": "CSS Property", "scope": ["support.type.property-name.css"], "fg": "#9DA9A0"},
        {"name": "CSS Value", "scope": ["support.constant.property-value.css"], "fg": "#A7C080"},
        {"name": "HTML Tag", "scope": ["entity.name.tag.html"], "fg": "#9DA9A0"},
        {"name": "Markdown Heading", "scope": ["markup.heading"], "fg": "#DBBC7F", "style": "bold"},
        {"name": "Markdown Bold", "scope": ["markup.bold"], "fg": "#D3C6AA", "style": "bold"},
        {"name": "Markdown Italic", "scope": ["markup.italic"], "fg": "#E69875", "style": "italic"},
        {"name": "Markdown Link", "scope": ["markup.underline.link"], "fg": "#7FBBB3"},
        {"name": "Markdown Code", "scope": ["markup.raw.code"], "fg": "#A7C080"},
        {"name": "Regex", "scope": ["string.regexp"], "fg": "#A7C080"},
        {"name": "Invalid", "scope": ["invalid"], "fg": "#E67E80", "style": "underline"},
        {"name": "Diff Added", "scope": ["markup.inserted", "diff.inserted"], "fg": "#A7C080"},
        {"name": "Diff Deleted", "scope": ["markup.deleted", "diff.deleted"], "fg": "#E67E80"},
        {"name": "Diff Modified", "scope": ["markup.changed", "diff.changed"], "fg": "#E69875"},
    ]
}

# ----------------------------------------------------------
# 9. GitHub Dark
# ----------------------------------------------------------
THEMES["github-dark"] = {
    "name": "GitHub Dark",
    "type": "dark",
    "colors": {
        "editor.background": "#0D1117", "editor.foreground": "#E6EDF3",
        "editorLineNumber.foreground": "#484F58", "editorLineNumber.activeForeground": "#8B949E",
        "editor.selectionBackground": "#264F78", "editor.selectionHighlightBackground": "#264F7880",
        "editor.findMatchBackground": "#A371F780", "editor.findMatchHighlightBackground": "#A371F740",
        "editorCursor.foreground": "#E6EDF3", "editor.lineHighlightBackground": "#161B22",
        "editorIndentGuide.background": "#21262D", "editorIndentGuide.activeBackground": "#484F58",
        "editorBracketMatch.border": "#58A6FF80", "editorGutter.background": "#0D1117",
        "editorWidget.background": "#161B22", "editorWidget.border": "#30363D",
        "editorSuggestWidget.background": "#161B22", "editorSuggestWidget.border": "#30363D",
        "editorSuggestWidget.selectedBackground": "#1F6FEB40",
        "editorHoverWidget.background": "#161B22", "editorHoverWidget.border": "#30363D",
        "editorGroup.border": "#30363D", "editorGroupHeader.tabsBackground": "#010409",
        "tab.activeBackground": "#0D1117", "tab.activeForeground": "#E6EDF3",
        "tab.inactiveBackground": "#010409", "tab.inactiveForeground": "#484F58",
        "tab.border": "#30363D", "tab.activeBorderTop": "#F78166",
        "sideBar.background": "#010409", "sideBar.foreground": "#8B949E",
        "sideBar.border": "#30363D", "sideBarTitle.foreground": "#E6EDF3",
        "sideBarSectionHeader.background": "#161B22",
        "list.activeSelectionBackground": "#1F6FEB40", "list.activeSelectionForeground": "#E6EDF3",
        "list.inactiveSelectionBackground": "#264F78", "list.hoverBackground": "#161B22",
        "list.foreground": "#8B949E",
        "activityBar.background": "#010409", "activityBar.foreground": "#8B949E",
        "activityBar.activeBorder": "#F78166", "activityBarBadge.background": "#1F6FEB",
        "activityBarBadge.foreground": "#FFFFFF",
        "statusBar.background": "#010409", "statusBar.foreground": "#8B949E",
        "statusBar.debuggingBackground": "#DA3633",
        "titleBar.activeBackground": "#010409", "titleBar.activeForeground": "#E6EDF3",
        "menu.background": "#161B22", "menu.foreground": "#E6EDF3",
        "menu.selectionBackground": "#1F6FEB40", "menu.separatorBackground": "#30363D",
        "button.background": "#238636", "button.foreground": "#FFFFFF",
        "button.hoverBackground": "#2EA043",
        "input.background": "#0D1117", "input.border": "#30363D", "input.foreground": "#E6EDF3",
        "dropdown.background": "#0D1117", "dropdown.border": "#30363D",
        "scrollbarSlider.background": "#484F5840", "scrollbarSlider.hoverBackground": "#484F5860",
        "panel.background": "#010409", "panel.border": "#30363D",
        "terminal.background": "#0D1117", "terminal.foreground": "#E6EDF3",
        "gitDecoration.addedResourceForeground": "#3FB950",
        "gitDecoration.modifiedResourceForeground": "#D29922",
        "gitDecoration.deletedResourceForeground": "#F85149",
        "gitDecoration.untrackedResourceForeground": "#3FB950",
        "gitDecoration.ignoredResourceForeground": "#484F58",
        "gitDecoration.conflictResourceForeground": "#DB6D28",
        "badge.background": "#1F6FEB", "badge.foreground": "#FFFFFF",
        "progressBar.background": "#1F6FEB", "focusBorder": "#1F6FEB80",
        "foreground": "#E6EDF3", "errorForeground": "#F85149",
        "textLink.foreground": "#58A6FF", "icon.foreground": "#484F58",
        "widget.shadow": "#00000080",
    },
    "tokens": [
        {"name": "Comment", "scope": ["comment"], "fg": "#8B949E", "style": "italic"},
        {"name": "String", "scope": ["string"], "fg": "#A5D6FF"},
        {"name": "Number", "scope": ["constant.numeric"], "fg": "#79C0FF"},
        {"name": "Boolean/Null", "scope": ["constant.language.boolean", "constant.language.null"], "fg": "#79C0FF"},
        {"name": "Keyword", "scope": ["keyword", "keyword.control"], "fg": "#FF7B72"},
        {"name": "Storage/Modifier", "scope": ["storage", "storage.type"], "fg": "#FF7B72"},
        {"name": "Function", "scope": ["entity.name.function", "support.function"], "fg": "#D2A8FF"},
        {"name": "Class/Type", "scope": ["entity.name.type", "entity.name.class", "support.type"], "fg": "#FFA657"},
        {"name": "Variable", "scope": ["variable"], "fg": "#E6EDF3"},
        {"name": "Parameter", "scope": ["variable.parameter"], "fg": "#FFA657"},
        {"name": "Property", "scope": ["variable.other.property"], "fg": "#79C0FF"},
        {"name": "Constant", "scope": ["variable.other.constant"], "fg": "#79C0FF"},
        {"name": "Tag", "scope": ["entity.name.tag"], "fg": "#7EE787"},
        {"name": "Attribute", "scope": ["entity.other.attribute-name"], "fg": "#79C0FF"},
        {"name": "Punctuation", "scope": ["punctuation", "meta.brace"], "fg": "#8B949E"},
        {"name": "Operator", "scope": ["keyword.operator"], "fg": "#FF7B72"},
        {"name": "Decorator", "scope": ["meta.decorator"], "fg": "#D2A8FF"},
        {"name": "JSON Key", "scope": ["meta.object-literal.key"], "fg": "#79C0FF"},
        {"name": "CSS Property", "scope": ["support.type.property-name.css"], "fg": "#79C0FF"},
        {"name": "CSS Value", "scope": ["support.constant.property-value.css"], "fg": "#A5D6FF"},
        {"name": "HTML Tag", "scope": ["entity.name.tag.html"], "fg": "#7EE787"},
        {"name": "Markdown Heading", "scope": ["markup.heading"], "fg": "#FFA657", "style": "bold"},
        {"name": "Markdown Bold", "scope": ["markup.bold"], "fg": "#E6EDF3", "style": "bold"},
        {"name": "Markdown Italic", "scope": ["markup.italic"], "fg": "#FFA657", "style": "italic"},
        {"name": "Markdown Link", "scope": ["markup.underline.link"], "fg": "#58A6FF"},
        {"name": "Markdown Code", "scope": ["markup.raw.code"], "fg": "#A5D6FF"},
        {"name": "Regex", "scope": ["string.regexp"], "fg": "#A5D6FF"},
        {"name": "Invalid", "scope": ["invalid"], "fg": "#F85149", "style": "underline"},
        {"name": "Diff Added", "scope": ["markup.inserted", "diff.inserted"], "fg": "#3FB950"},
        {"name": "Diff Deleted", "scope": ["markup.deleted", "diff.deleted"], "fg": "#F85149"},
        {"name": "Diff Modified", "scope": ["markup.changed", "diff.changed"], "fg": "#D29922"},
    ]
}

# ----------------------------------------------------------
# 10. One Dark Pro
# ----------------------------------------------------------
THEMES["one-dark-pro"] = {
    "name": "One Dark Pro",
    "type": "dark",
    "colors": {
        "editor.background": "#282C34", "editor.foreground": "#ABB2BF",
        "editorLineNumber.foreground": "#495162", "editorLineNumber.activeForeground": "#ABB2BF",
        "editor.selectionBackground": "#3D4450", "editor.selectionHighlightBackground": "#3D445080",
        "editor.findMatchBackground": "#4D78CC80", "editor.findMatchHighlightBackground": "#4D78CC40",
        "editorCursor.foreground": "#528BFF", "editor.lineHighlightBackground": "#2C313C",
        "editorIndentGuide.background": "#3B4048", "editorIndentGuide.activeBackground": "#495162",
        "editorBracketMatch.border": "#528BFF80", "editorGutter.background": "#282C34",
        "editorWidget.background": "#21252B", "editorWidget.border": "#3B4048",
        "editorSuggestWidget.background": "#21252B", "editorSuggestWidget.border": "#3B4048",
        "editorSuggestWidget.selectedBackground": "#3D4450",
        "editorHoverWidget.background": "#21252B", "editorHoverWidget.border": "#3B4048",
        "editorGroup.border": "#3B4048", "editorGroupHeader.tabsBackground": "#21252B",
        "tab.activeBackground": "#282C34", "tab.activeForeground": "#ABB2BF",
        "tab.inactiveBackground": "#21252B", "tab.inactiveForeground": "#495162",
        "tab.border": "#3B4048", "tab.activeBorderTop": "#528BFF",
        "sideBar.background": "#21252B", "sideBar.foreground": "#ABB2BF",
        "sideBar.border": "#3B4048", "sideBarTitle.foreground": "#ABB2BF",
        "sideBarSectionHeader.background": "#282C34",
        "list.activeSelectionBackground": "#3D4450", "list.activeSelectionForeground": "#FFFFFF",
        "list.inactiveSelectionBackground": "#3D445080", "list.hoverBackground": "#2C313C",
        "list.foreground": "#ABB2BF",
        "activityBar.background": "#21252B", "activityBar.foreground": "#ABB2BF",
        "activityBar.activeBorder": "#528BFF", "activityBarBadge.background": "#528BFF",
        "activityBarBadge.foreground": "#FFFFFF",
        "statusBar.background": "#21252B", "statusBar.foreground": "#ABB2BF",
        "statusBar.debuggingBackground": "#E06C75",
        "titleBar.activeBackground": "#21252B", "titleBar.activeForeground": "#ABB2BF",
        "menu.background": "#21252B", "menu.foreground": "#ABB2BF",
        "menu.selectionBackground": "#3D4450", "menu.separatorBackground": "#3B4048",
        "button.background": "#528BFF", "button.foreground": "#FFFFFF",
        "button.hoverBackground": "#629CFF",
        "input.background": "#21252B", "input.border": "#3B4048", "input.foreground": "#ABB2BF",
        "dropdown.background": "#21252B", "dropdown.border": "#3B4048",
        "scrollbarSlider.background": "#49516240", "scrollbarSlider.hoverBackground": "#49516260",
        "panel.background": "#21252B", "panel.border": "#3B4048",
        "terminal.background": "#282C34", "terminal.foreground": "#ABB2BF",
        "gitDecoration.addedResourceForeground": "#98C379",
        "gitDecoration.modifiedResourceForeground": "#E5C07B",
        "gitDecoration.deletedResourceForeground": "#E06C75",
        "gitDecoration.untrackedResourceForeground": "#98C379",
        "gitDecoration.ignoredResourceForeground": "#495162",
        "gitDecoration.conflictResourceForeground": "#E5C07B",
        "badge.background": "#528BFF", "badge.foreground": "#FFFFFF",
        "progressBar.background": "#528BFF", "focusBorder": "#528BFF80",
        "foreground": "#ABB2BF", "errorForeground": "#E06C75",
        "textLink.foreground": "#61AFEF", "icon.foreground": "#495162",
        "widget.shadow": "#00000060",
    },
    "tokens": [
        {"name": "Comment", "scope": ["comment"], "fg": "#7F848E", "style": "italic"},
        {"name": "String", "scope": ["string"], "fg": "#98C379"},
        {"name": "Number", "scope": ["constant.numeric"], "fg": "#D19A66"},
        {"name": "Boolean/Null", "scope": ["constant.language.boolean", "constant.language.null"], "fg": "#D19A66"},
        {"name": "Keyword", "scope": ["keyword", "keyword.control"], "fg": "#C678DD"},
        {"name": "Storage/Modifier", "scope": ["storage", "storage.type"], "fg": "#C678DD"},
        {"name": "Function", "scope": ["entity.name.function", "support.function"], "fg": "#61AFEF"},
        {"name": "Class/Type", "scope": ["entity.name.type", "entity.name.class", "support.type"], "fg": "#E5C07B"},
        {"name": "Variable", "scope": ["variable"], "fg": "#E06C75"},
        {"name": "Parameter", "scope": ["variable.parameter"], "fg": "#E06C75"},
        {"name": "Property", "scope": ["variable.other.property"], "fg": "#ABB2BF"},
        {"name": "Constant", "scope": ["variable.other.constant"], "fg": "#D19A66"},
        {"name": "Tag", "scope": ["entity.name.tag"], "fg": "#E06C75"},
        {"name": "Attribute", "scope": ["entity.other.attribute-name"], "fg": "#E5C07B"},
        {"name": "Punctuation", "scope": ["punctuation", "meta.brace"], "fg": "#ABB2BF"},
        {"name": "Operator", "scope": ["keyword.operator"], "fg": "#56B6C2"},
        {"name": "Decorator", "scope": ["meta.decorator"], "fg": "#61AFEF"},
        {"name": "JSON Key", "scope": ["meta.object-literal.key"], "fg": "#E06C75"},
        {"name": "CSS Property", "scope": ["support.type.property-name.css"], "fg": "#ABB2BF"},
        {"name": "CSS Value", "scope": ["support.constant.property-value.css"], "fg": "#D19A66"},
        {"name": "HTML Tag", "scope": ["entity.name.tag.html"], "fg": "#E06C75"},
        {"name": "Markdown Heading", "scope": ["markup.heading"], "fg": "#61AFEF", "style": "bold"},
        {"name": "Markdown Bold", "scope": ["markup.bold"], "fg": "#C678DD", "style": "bold"},
        {"name": "Markdown Italic", "scope": ["markup.italic"], "fg": "#E06C75", "style": "italic"},
        {"name": "Markdown Link", "scope": ["markup.underline.link"], "fg": "#61AFEF"},
        {"name": "Markdown Code", "scope": ["markup.raw.code"], "fg": "#98C379"},
        {"name": "Regex", "scope": ["string.regexp"], "fg": "#98C379"},
        {"name": "Invalid", "scope": ["invalid"], "fg": "#E06C75", "style": "underline"},
        {"name": "Diff Added", "scope": ["markup.inserted", "diff.inserted"], "fg": "#98C379"},
        {"name": "Diff Deleted", "scope": ["markup.deleted", "diff.deleted"], "fg": "#E06C75"},
        {"name": "Diff Modified", "scope": ["markup.changed", "diff.changed"], "fg": "#E5C07B"},
    ]
}

# ============================================================
# 生成 JSON 文件
# ============================================================

def build_theme_json(theme_def):
    token_colors = []
    for t in theme_def["tokens"]:
        settings = {"foreground": t["fg"]}
        if "style" in t:
            settings["fontStyle"] = t["style"]
        token_colors.append({
            "name": t["name"],
            "scope": t["scope"],
            "settings": settings
        })

    return {
        "name": theme_def["name"],
        "type": theme_def["type"],
        "semanticHighlighting": True,
        "colors": theme_def["colors"],
        "tokenColors": token_colors
    }

os.makedirs(THEMES_DIR, exist_ok=True)

for key, theme_def in THEMES.items():
    filename = f"{key}.json"
    filepath = os.path.join(THEMES_DIR, filename)
    theme_json = build_theme_json(theme_def)
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(theme_json, f, indent=2, ensure_ascii=False)
    print(f"  ✓ {filename} ({theme_def['name']})")

print(f"\n共生成 {len(THEMES)} 个主题文件")
